services:
  postgres:
    image: postgres:16
    container_name: fintrack-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack_password
      POSTGRES_DB: fintrack_db
    volumes:
      - fintrack_postgres_data:/var/lib/postgresql/data

volumes:
  fintrack_postgres_data: